Feat/1 redux setting
payw-org/ttock-ttack pull request #3
Opened 2021-01-06 14:56 UTC by JeongBin0227

타입스크립트로 redux setting 했습니다.

참고) https://www.freecodecamp.org/news/how-to-use-redux-in-your-react-typescript-app/

2021-01-06 14:57 UTC, JeongBin0227 commented
우선 임시데이터로 만들었습니다.

2021-01-09 13:17 UTC, choibumsu requested changes

2021-01-09 13:17 UTC, choibumsu commented on package.json
> +    "@types/react-dom": "^16.9.10",
정빈 버전 다운한 이유는 뭐야??

2021-01-09 13:17 UTC, choibumsu commented on src/index.tsx
> +import { Provider } from "react-redux"
정빈 Prettier 되는지 확인 부탁해~
singleQuote 사용하고, 세미콜론 없는 걸로 설정해놨는데, 적용 안 된거 같아

2021-01-11 13:19 UTC, YooInKeun commented on src/type.d.tsx
> +  }
첫째출 제외하고 indentation이 적용된 거 같은데 의도된 건가요?
의도된 게 아니라면 Prettier 설정에 추가하면 좋을라나..

2021-02-18 01:33 UTC, closed without merging